name: Generate Redirects

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run redirect generator
      run: node generate.js

    - name: Commit and push changes
      env:
        PERSONAL_TOKEN: ${{ secrets.LINUS_PAT_FOR_ACTIONS }}
      run: |
        git config user.name "Linus Kang"
        git config user.email "linuskang09@gmail.com"
        git remote set-url origin https://x-access-token:${PERSONAL_TOKEN}@github.com/${{ github.repository }}.git
        git add .
        git commit -m "Auto-generate redirect pages" || echo "No changes to commit"
        git push origin HEAD:main
